
spring:
  datasource:
    url: jdbc:mysql://10.42.206.2:3306/ExitApp
    username: zentalentdev
    password: 3k2@M5t6
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
   